dist: trusty
group: edge
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - VARNISH_VERSION=5.0.0

matrix:
  allow_failures:
    - php: 7.2
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.* VARNISH_VERSION=3.0 COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.0
      env:
        - VARNISH_VERSION=4.1
        - DOCCHECK=true

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

before_script:
  # Install Varnish
  - |
    set -e
    if [ "$VARNISH_VERSION" = "5.0.0" ]; then
      wget https://repo.varnish-cache.org/pkg/${VARNISH_VERSION}/varnish_${VARNISH_VERSION}-1_amd64.deb
      sudo apt-get install -qq libjemalloc1
      sudo dpkg -i varnish_${VARNISH_VERSION}-1_amd64.deb
      sudo apt-get update -qq
      sudo apt-get -f install
    else
      curl http://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
      echo "deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-${VARNISH_VERSION}" | sudo tee -a /etc/apt/sources.list
      sudo apt-get update -qq
      sudo apt-get install -qq varnish
    fi
  - if [ "$DOCCHECK" = true ]; then sudo apt-get install -qq python-sphinx enchant; fi
  - if [ "$DOCCHECK" = true ]; then sudo pip install -r doc/requirements.txt; fi
  # Install NGINX
  - sh ./tests/install-nginx.sh
  # Starting webserver
  - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ]; then ./tests/ci/install-apache-hhvm.sh; fi

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - if [[ "$DOCCHECK" = true ]]; then make -C doc SPHINXOPTS='-nW' html; fi
  - if [[ "$DOCCHECK" = true ]]; then make -C doc spelling; fi

after_script:
  # avoid uploading the code coverage for HHVM as it cannot generate it (PHPUnit dropped the old HHVM driver and the 
  # XDebug API is not implemented in HHVM 3.5) and we don't want to cancel the Scrutinizer analysis by notifying
  # it than no coverage data is available
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos_nginx_error.log
  - cat /tmp/fos_nginx_access.log
  - cat /tmp/hhvm.log
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/other_vhosts_access.log
