language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  # Install Varnish
  - sudo apt-get update -qq
  - sudo apt-get install -qq varnish
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ]; then ./tests/ci/install-apache.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = 'hhvm' ]; then ./tests/ci/install-apache-hhvm.sh; fi"
  # Install deps
  - composer update --dev --prefer-source

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
