language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - VARNISH_VERSION=4.0

matrix:
  include:
    - php: hhvm
      dist: trusty
    - php: 5.5
      env: VARNISH_VERSION=3.0
    - php: 5.3
      env: SYMFONY_VERSION=2.3.* VARNISH_VERSION=4.0 COMPOSER_FLAGS="--prefer-lowest"

branches:
  only:
    - master
    # Build maintenance branches for older releases if needed. such branches should be named like "1.2"
    - '/^\d+\.\d+$/'

before_script:
  # Install deps
  - composer update $COMPOSER_FLAGS --dev --prefer-source --no-interaction
  - bash -c "if [[ '$TRAVIS_PHP_VERSION' == '7.'* ]] ; then wget https://phar.phpunit.de/phpunit-5.7.phar; fi"
  # Install Varnish
  - curl http://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
  - echo "deb http://repo.varnish-cache.org/ubuntu/ precise varnish-${VARNISH_VERSION}" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq varnish python-sphinx enchant
  - sudo pip install -r doc/requirements.txt
  # Install NGINX
  - sh ./tests/install-nginx.sh
  # Starting webserver
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ]; then ./tests/ci/install-apache.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = 'hhvm' ]; then ./tests/ci/install-apache-hhvm.sh; fi"

script:
  - bash -c "if [[ '$TRAVIS_PHP_VERSION' == '7.'* ]] ; then php phpunit-5.7.phar --coverage-clover=coverage.clover; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' \< '7' ]; then phpunit --coverage-clover=coverage.clover; fi"
  - make -C doc SPHINXOPTS='-nW' html
  - make -C doc spelling

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat /tmp/fos_nginx_error.log
  - cat /tmp/fos_nginx_access.log
