name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpstan-src:
    name: PHPStan src
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull in optional dependencies
        run: |
          composer require --no-update symfony/http-kernel:^5.0 symfony/event-dispatcher:^5.0 symfony/process:^5.0 phpunit/phpunit toflar/psr6-symfony-http-cache-store:^3.0
          composer update --no-dev --no-progress

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress

  phpstan-tests:
    name: PHPStan tests
    runs-on: ubuntu-latest
    env:
      REQUIRE_DEV: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull in optional dependencies
        run: |
          composer require --no-update phpunit/phpunit toflar/psr6-symfony-http-cache-store:^3.0
          composer update --no-progress

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress -c phpstan.tests.neon.dist

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --dry-run --diff
